page_title                                : Tilfaz

ios_app_id                                : 1668359578

appstore_link                             : https://apps.apple.com/app/1668359578

app_icon                                  : assets/appicon.png
app_name                                  : Tilfaz
app_description                           : Discover Tilfaz! Advanced search, superior video playback, and seamless sync across Apple devices. Welcome to your ultimate TV experience!

enable_smart_app_banner                   : true

email_address                             : support@tilfaz.app

features                                  :

  - title                                 : Your Content Everywhere
    description                           : You can use Tilfaz on iPhone, iPad, Apple TV, and Mac.
    fontawesome_icon_name                 : apple
    
  - title                                 : Cloud Syncing
    description                           : Your library is synchronized securely and instantly across all of your devices.
    fontawesome_icon_name                 : cloud

  - title                                 : Global Search
    description                           : Advanced search engine that helps you find what you're looking for in your library.
    fontawesome_icon_name                 : magnifying-glass

  - title                                 : Advanced Player
    description                           : Supports various formats, subtitle, audio tracks, changing playback speed, and more…
    fontawesome_icon_name                 : play

  - title                                 : Multiple Sources
    description                           : Add as many Xtream and M3U sources as you want!
    fontawesome_icon_name                 : list

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
